<body>
<div class="container">
    <h2>КОРЗИНА</h2>
<div <?php $sum = 0; ?></div>
<?php foreach ($products as $product): ?>
    <div class="card-image"><img src="<?php echo $product->getImageLink(); ?>" alt=""></div>
    <div class="card-details">
        <div class="card-name"><?php echo ucfirst($product->getName()); ?></div>
        <div class="card-price"><?php echo $product->getPrice() . " руб"; ?></div>
        <div class="card-wheel">
            <span> <?php $quantity = $cartProducts[$product->getId()]->getQuantity(); echo $quantity . " шт"; ?></span>
        </div>
    </div>
    <div <?php $sum += $product->getPrice()*$quantity; ?></div>
<?php endforeach; ?>
    <div class="checkout-total">
        <h6>Итого</h6>
        <p><?php echo $sum ." руб"; ?></p><a href="/order"><button type="submit" class="btn">Оформить заказ </button>
    </div>
</body>

<style>
    * {
        box-sizing: border-box;
        margin: 0;
        padding: 0;
    }
    body {
        font-family: "Poppins", sans-serif;
        height: 100%;
        width: 100%;
        margin: auto;
        padding: 50px 0px 0px;
        color: #4E5150;
    }

    .card-image {
        width: 25%;
    }

    img {
        width: 100%;
        border-radius: 10px;
    }

    .card-details {
        display: flex;
        flex-direction: column;
    }

    .card-name {
        font-size: 30px;
        font-weight: 500;
    }

    .card-price {
        font-size: 30px;
        font-weight: 500;
        color: #F2994A;
        margin-top: 5px;
    }

    span {
        color: #4E5150;
    }

    .card-wheel {
        margin-top: auto;
        border: 2px solid #4e515085;
        width: 90px;
        padding: 10px 40px;
        border-radius: 10px;
        font-size: 20px;
        display: flex;
        justify-content: center;
    }

    .checkout-total {
        display: flex;
        font-size: 35px;
        padding: 35px 0px;
        border-top: 1px solid #BDBDBD;
        justify-content: space-between;
    }

    p {
        font-size: 35px;
        font-weight: 10;
    }

    body {
        width: 92%;
    }

    .btn {
        display: flex;
        background-color: lightgray;
        color: black;
        padding: 8px 0px;
        font-size: 20px;
        width: 100%;
        opacity: 50;
    }

    .btn:hover {
        color: maroon;
        opacity: 100;
    }

</style>