<body>
<header>
    <div class="header-cart">
        <a href="/user-cart"><button type="submit" class="btn-cart">
            <img class="img-cart" src="https://cdn-icons-png.flaticon.com/512/263/263142.png">
        </button></a>
    </div>
</header>
<h3>Catalog</h3>

    <div class="container">
        <div class="card-deck">
            <?php foreach ($products as $product): ?>
                <div class="card text-center">
                    <form method="POST" onsubmit="return false" class="addProductForm">
                    <div class="card-header">
                        <img class="card-img-top" src=<?php echo $product->getImageLink(); ?> alt="Card image">
                        <div class="card-body">
                            <p class="card-text text-muted"><?php echo ucfirst($product->getName()); ?> </p>
                            <h5 class="card-title">Description!</h5>
                            <div class="card-footer">
                                <?php echo $product->getPrice() . " p"; ?><br>
                                <label>
                                    <input type="text" placeholder="product_id" name="product_id" hidden="" value="<?php echo $product->getId(); ?>">
                                    <input type="text" placeholder="quantity" name="quantity" class="quantity">
                                </label>
                                <button type="submit" class="btn">Add to cart</button>
                            </div>
                        </div>
                    </div>
                    </form>
                </div>
            <?php endforeach; ?>
        </div>
    </div>

</body>
<script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
<script>
    $("document").ready(function() {
        $('.addProductForm').submit(function() {
            $.ajax({
                type: "POST",
                url: "/add-product",
                // dataType: 'html',
                data: $(this).serialize(),
                success: function() {
                    console.log('done');
                    $('input.quantity').val('');
                }
            })
        });
    });
</script>
<style>
    body {
        font-family: "Josefin Slab";
    }

    h3 {
        font-size: 2.2rem;
        /*margin-top: 80px;*/
        text-align: center;
        color: navy;
    }

    .container {
        display: flex;
        flex-wrap: wrap;
        max-width: 255px;
        margin: 1vw auto;
        position: relative;
    }

    a {
        text-align: center;
        color: darkblue;
        text-decoration: none;
    }

    a:hover {
        text-align: center;
        color: maroon;
        text-decoration: none;
    }

    .card {
        max-width: 16rem;
        margin-bottom: 6px;
    }

    .card:hover {
        box-shadow: 1px 2px 10px lightgray;
        transition: 0.2s;
    }

    .card-header {
        text-align: center;
        font-size: 13px;
        color: red;
        background-color: white;
        margin-bottom: 6px;
    }

    .card-img-top{
        max-width:16rem;
    }

    .text-muted {
        text-align: center;
        font-weight: bold;
        font-size: 40px;
    }

    .card-title{
        text-align: center;
        font-size: 14px;
        color: cornflowerblue;
        background-color: white;
    }

    .card-footer{
        text-align: center;
        font-weight: bold;
        color: navy;
        font-size: 20px;
        background-color: white;
    }
    .btn {
        background-color: aliceblue;
        color: darkblue;
        padding: 12px 20px;
        font-size: 20px;
        margin: 16px 0;
        width: 80%;
        opacity: 50;
    }

    .btn:hover {
        color: maroon;
        opacity: 100;
    }

    header {
        height:60px;
        width: 100%;
        background: lightblue;
        text-align: right;
        padding-top:10px;
    }

    .img-cart {
        width: 45px;
    }

    .header-cart {
        position:relative;
        display:inline-block;
        margin-right:40px;
    }
</style>

