<form action="" method="POST">
    <div class="container">
        <h1>Оформление заказа</h1>
        <p>Пожалуйста, заполните эту форму.</p>
        <hr>
        <label for="name"><b>Name</b></label>
        <?php if (isset($errors['name'])): ?>
            <label style="color: red"><?php echo $errors['name']; ?></label>
        <?php endif; ?>
        <input type="text" placeholder="Enter Name" name="name" id="name" required>
        <label for="last-name"><b>Last name</b></label>
        <?php if (isset($errors['last-name'])): ?>
            <label style="color: red"><?php echo $errors['last-name']; ?></label>
        <?php endif; ?>
        <input type="text" placeholder="Enter Last Name" name="last-name" id="last-name" required>
        <label for="number"><b>Number of phone</b></label>
        <?php if (isset($errors['number'])): ?>
            <label style="color: red"><?php echo $errors['number']; ?></label>
        <?php endif; ?>
        <input type="text" placeholder="Enter Number Of Phone" name="number" id="number" required>
        <label for="address"><b>Address</b></label>
        <?php if (isset($errors['address'])): ?>
            <label style="color: red"><?php echo $errors['address']; ?></label>
        <?php endif; ?>
        <input type="text" placeholder="Enter Address" name="address" id="address" required>
        <hr>
<!--        <hr>-->
<!--        <p>The information about products</p>-->
<!--        <input type="text" placeholder="Enter Name" name="name" id="name" required>-->
<!--        <hr>-->
        <button type="submit" class="orderbtn">Order</button>
    </div>
</form>

<style>
    body {
        font-family: Arial, Helvetica, sans-serif;
        background-color: white;
    }

    * {
        box-sizing: border-box;
    }

    /* Add padding to containers */
    .container {
        padding: 16px;
        background-color: white;
    }

    /* Full-width input fields */
    input[type=text] {
        width: 100%;
        padding: 15px;
        margin: 5px 0 22px 0;
        display: inline-block;
        border: none;
        background: #f1f1f1;
    }

    input[type=text]:focus, input[type=password]:focus {
        background-color: #ddd;
        outline: none;
    }

    /* Overwrite default styles of hr */
    hr {
        border: 1px solid #f1f1f1;
        margin-bottom: 25px;
    }

    /* Set a style for the submit button */
    .orderbtn {
        background-color: darkorchid;
        color: white;
        padding: 16px 20px;
        margin: 8px 0;
        border: none;
        cursor: pointer;
        width: 100%;
        opacity: 0.9;
    }

    .orderbtn:hover {
        opacity: 1;
    }

    /* Add a blue text color to links */
    a {
        color: dodgerblue;
    }

</style>