<link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
<body>
<div class="wrapper">
    <form action="" method="POST">
        <h1>Add products</h1>
        <div class="input-box">
            <?php if (isset($errors['product_id'])): ?>
                <label style="color: red"><?php echo $errors['product_id']; ?></label>
            <?php endif; ?>
            <input type="text" placeholder="product_id" name="product_id">
        </div>
        <div class="input-box">
            <?php if (isset($errors['quantity'])): ?>
                <label style="color: red"><?php echo $errors['quantity']; ?></label>
            <?php endif; ?>
            <input type="text" placeholder="quantity" name="quantity">
        </div>

        <button type="submit" class="btn">Add</button>
    </form>
</div>
</body>

<style>

    @import url('https://fonts.googleapis.com/css2?family=Poppins&display=swap');

    *
    {
        padding: 0;
        margin: 0;
        box-sizing: border-box;
        font-family: 'Poppins', sans-serif;

    }
    body{
        display: flex;
        justify-content: center;
        align-items: center;
        min-height: 100vh;
        background:url(https://img.playbook.com/GkXdxuPUJybZqdTcLNt124xUnMD_bK19dxy4Z8SczhE/Z3M6Ly9wbGF5Ym9v/ay1hc3NldHMtcHVi/bGljLzJhNWYxODk1/LTE0ZWMtNGNjMi1h/ZGZlLTRkMzQxYWYw/Zjk1OQ);
        background-size: cover;
        background-position: center;
    }
    .wrapper {
        width: 420px;
        background: transparent;
        border:2px solid rgba(255, 255, 255, .2);
        backdrop-filter:blur(20px);
        box-shadow: 0 0 10px rgba(0 , 0 , 0 , .2);
        color: #fff;
        border-radius: 10px;
        padding: 30px 40px;

    }
    .wrapper h1{
        font-size: 36px;
        text-align: center;
    }
    .wrapper .input-box {
        position: relative;
        width: 100%;
        height: 50px;
        margin: 30px 0;
    }

    .input-box input{
        width: 100%;
        height: 100%;
        background: transparent;
        border: none;
        outline: none;
        border: 2px solid rgba(255, 255, 255, .2);
        border-radius: 40px;
        font-size: 16px;
        color: #fff;
        padding: 20px 45px 20px 20px;
    }
    .input-box input::placeholder{
        color: #fff;
    }
    .input-box i{
        position: absolute;
        right: 20px;
        top: 50%;
        transform: translateY(-50%);
        font-size: 20px;

    }
    .wrapper .btn{
        width: 100%;
        height: 45px;
        border-radius: 40px;
        border: none;
        outline: none;
        background: #fff;
        box-shadow: 0 0 10px rgba(0 , 0 , 0 , .1);
        cursor: pointer;
        font-size: 16px;
        color: #333;
        font-weight: 600;
    }
</style>